# Generated by Django 5.2.4 on 2025-07-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
